--- #YAML:1.0
name:               CORBA-XS
version:            0.63_01
abstract:           IDL compiler to extension interface between Perl and C code
author:
    - Francois PERRAD (francois.perrad@gadz.org)
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    CORBA::C:     2.6
    CORBA::IDL:   2.6
    CORBA::Perl:  0.41
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
