--- #YAML:1.0
name:                CORBA-XS
version:             0.62
abstract:            IDL compiler to extension interface between Perl and C code
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.3201
distribution_type:   module
requires:     
    CORBA::C:                      2.6
    CORBA::IDL:                    2.6
    CORBA::Perl:                   0.41
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Francois PERRAD (francois.perrad@gadz.org)
